### ISSUE TITLE
[Bug]: Error while compiling nrf52_promicro_diy_tcxo firmware

### ISSUE THREAD

**Issue by radonslide** [meshtastic/Meshtastic-device#10203]
### Category

Other, Hardware Compatibility

### Hardware

DIY

### Is this bug report about any UI component firmware like InkHUD or Meshtatic UI (MUI)?

- [ ] Meshtastic UI aka MUI colorTFT
- [ ] InkHUD ePaper
- [ ] OLED slide UI on any display

### Firmware Version

2.7.23.6b15571

### Description

After today's master source update to 2.7.23.6b15571, I can no longer compile firmware for my nrf52_promicro_diy_tcxo hardware.
You can see the attempt in the attached log file.
Try compiling fw for other hardware (rak4631) shown same issues with "CST3530"

Everything still worked with version 2.7.23.c1bee82.

### Relevant log output

```Shell
Compiling .pio/build/nrf52_promicro_diy_tcxo/src/detect/ScanI2C.cpp.o
Compiling .pio/build/nrf52_promicro_diy_tcxo/src/detect/ScanI2CConsumer.cpp.o
Compiling .pio/build/nrf52_promicro_diy_tcxo/src/detect/ScanI2CTwoWire.cpp.o
Compiling .pio/build/nrf52_promicro_diy_tcxo/src/detect/reClockI2C.cpp.o
Compiling .pio/build/nrf52_promicro_diy_tcxo/src/gps/GPS.cpp.o
In file included from src/detect/ScanI2C.cpp:1:
src/detect/ScanI2C.h:99:9: error: redeclaration of 'CST3530'
   99 |         CST3530,
      |         ^~~~~~~
src/detect/ScanI2C.h:92:9: note: previous declaration 'CST3530'
   92 |         CST3530,
      |         ^~~~~~~
Compiling .pio/build/nrf52_promicro_diy_tcxo/src/gps/GPSUpdateScheduling.cpp.o
*** [.pio/build/nrf52_promicro_diy_tcxo/src/detect/ScanI2C.cpp.o] Error 1
In file included from src/detect/ScanI2CConsumer.h:3,
                 from src/detect/ScanI2CConsumer.cpp:1:
src/detect/ScanI2C.h:99:9: error: redeclaration of 'CST3530'
   99 |         CST3530,
      |         ^~~~~~~
src/detect/ScanI2C.h:92:9: note: previous declaration 'CST3530'
   92 |         CST3530,
      |         ^~~~~~~
*** [.pio/build/nrf52_promicro_diy_tcxo/src/detect/ScanI2CConsumer.cpp.o] Error 1
In file included from src/modules/Telemetry/Sensor/TelemetrySensor.h:9,
                 from src/modules/Telemetry/Sensor/nullSensor.h:9,
                 from src/power.h:32,
                 from src/Power.cpp:16:
src/detect/ScanI2C.h:99:9: error: redeclaration of 'CST3530'
   99 |         CST3530,
      |         ^~~~~~~
src/detect/ScanI2C.h:92:9: note: previous declaration 'CST3530'
   92 |         CST3530,
      |         ^~~~~~~
In file included from src/graphics/Screen.h:5,
                 from src/PowerFSM.cpp:16:
src/detect/ScanI2C.h:99:9: error: redeclaration of 'CST3530'
   99 |         CST3530,
      |         ^~~~~~~
src/detect/ScanI2C.h:92:9: note: previous declaration 'CST3530'
   92 |         CST3530,
      |         ^~~~~~~
In file included from src/main.h:7,
                 from src/RedirectablePrint.cpp:6:
src/detect/ScanI2C.h:99:9: error: redeclaration of 'CST3530'
   99 |         CST3530,
      |         ^~~~~~~
src/detect/ScanI2C.h:92:9: note: previous declaration 'CST3530'
   92 |         CST3530,
      |         ^~~~~~~
In file included from src/detect/ScanI2CTwoWire.h:13,
                 from src/detect/ScanI2CTwoWire.cpp:1:
src/detect/ScanI2C.h:99:9: error: redeclaration of 'CST3530'
   99 |         CST3530,
      |         ^~~~~~~
src/detect/ScanI2C.h:92:9: note: previous declaration 'CST3530'
   92 |         CST3530,
      |         ^~~~~~~
In file included from src/detect/ScanI2CTwoWire.h:13,
                 from src/detect/reClockI2C.h:5,
                 from src/detect/reClockI2C.cpp:1:
src/detect/ScanI2C.h:99:9: error: redeclaration of 'CST3530'
   99 |         CST3530,
      |         ^~~~~~~
src/detect/ScanI2C.h:92:9: note: previous declaration 'CST3530'
   92 |         CST3530,
      |         ^~~~~~~
In file included from src/main.h:7,
                 from src/concurrency/NotifiedWorkerThread.cpp:3:
src/detect/ScanI2C.h:99:9: error: redeclaration of 'CST3530'
   99 |         CST3530,
      |         ^~~~~~~
src/detect/ScanI2C.h:92:9: note: previous declaration 'CST3530'
   92 |         CST3530,
      |         ^~~~~~~
*** [.pio/build/nrf52_promicro_diy_tcxo/src/detect/reClockI2C.cpp.o] Error 1
In file included from src/main.h:7,
                 from src/gps/GPS.cpp:17:
src/detect/ScanI2C.h:99:9: error: redeclaration of 'CST3530'
   99 |         CST3530,
      |         ^~~~~~~
src/detect/ScanI2C.h:92:9: note: previous declaration 'CST3530'
   92 |         CST3530,
      |         ^~~~~~~
*** [.pio/build/nrf52_promicro_diy_tcxo/src/detect/ScanI2CTwoWire.cpp.o] Error 1
*** [.pio/build/nrf52_promicro_diy_tcxo/src/Power.cpp.o] Error 1
*** [.pio/build/nrf52_promicro_diy_tcxo/src/PowerFSM.cpp.o] Error 1
*** [.pio/build/nrf52_promicro_diy_tcxo/src/RedirectablePrint.cpp.o] Error 1
*** [.pio/build/nrf52_promicro_diy_tcxo/src/concurrency/NotifiedWorkerThread.cpp.o] Error 1
*** [.pio/build/nrf52_promicro_diy_tcxo/src/gps/GPS.cpp.o] Error 1
===================================================================== [FAILED] Took 14.39 seconds =====================================================================

Environment              Status    Duration
-----------------------  --------  ------------
nrf52_promicro_diy_tcxo  FAILED    00:00:14.393
```

**Comment by thebentern** [comment]
Due to a botched merge conflict resolution. Fixing that up in this PR #10204 . I'll merge in a few
