### PR TITLE
fix strlcpy compile error in Ubuntu 22.04

### PR DESCRIPTION
**Pull request by mverch67**
The portduino _native-xxx_ targets do not compile on Ubuntu 22.04 (arm64), I get the following compile error:

```c++
src/mqtt/MQTT.cpp: In member function ‘bool MQTT::publish(const char*, const uint8_t*, size_t, bool)’:
src/mqtt/MQTT.cpp:476:9: error: ‘strlcpy’ was not declared in this scope; did you mean ‘strncpy’?
  476 |         strlcpy(msg->topic, topic, sizeof(msg->topic));
      |         ^~~~~~~
      |         strncpy

```      
This is due to strlcpy (introduced in PR https://github.com/meshtastic/firmware/pull/8320) is not a POSIX function and not part of glibc.

However, it is contained in libbsd so this PR modifies the build command line to optionally include this library if it is installed:

`!pkg-config --cflags --libs libbsd-overlay --silence-errors`

Install _strlcpy_ with `sudo apt install libbsd-dev` on Ubuntu if affected by this same error.

## 🤝 Attestations

- [x] I have tested that my proposed changes behave as described.
- [x] I have tested that my proposed changes do not cause any obvious regressions on the following devices:
  - [ ] Heltec (Lora32) V3
  - [ ] LilyGo T-Deck
  - [ ] LilyGo T-Beam
  - [ ] RAK WisBlock 4631
  - [ ] Seeed Studio T-1000E tracker card
  - [x] Other (please specify below)
    - [x] native
    - [x] native-tft
    - [x] native-fb
    - [x] native-tft-debug

### CODE REVIEW

**Comment by jp-bennett** [comment]
@vidplace7 does this fix your compile error too?

**Comment by vidplace7** [comment]
This needs to be added to debian/control and meshtasticd.spec.rpkg as well :+1:

File: variants/native/portduino/platformio.ini
Comment (vidplace7) [inline variants/native/portduino/platformio.ini:1]: @mverch67 can we simply define this once in arch/portduino? (so it's included in the openwrt/buildroot/etc builds)

Comment (mverch67) [reply variants/native/portduino/platformio.ini:1]: I'm not sure if the `!pkg-config` instructions get inherited across environments. I ever tried it and that did not work that time.

Comment (vidplace7) [reply variants/native/portduino/platformio.ini:1]: We can keep it the way you've done it and I'll add the libbsd dep manually in the openwrt packaging :+1:

**Review by vidplace7 — APPROVED** [review]
This PR is good to merge as-is along with it's cousin #8533 
I'd love to get this included in a release before we cut a Beta, since Ubuntu 22.04 / Debian 12 are currently broken 🙏

File: variants/native/portduino/platformio.ini
Comment (mverch67) [reply variants/native/portduino/platformio.ini:1]: I just tried it and the inheritance fails with linker errors (i.e. these !pkg-config can only be in leave environments):

```
/usr/bin/ld: .pio/build/native-tft/lib5e2/liblvgl.a(lv_libinput.c.o): in function `_delete':
/home/manuel/Documents/PlatformIO/Projects/firmware-elecrow/.pio/libdeps/native-tft/lvgl/src/drivers/libinput/lv_libinput.c:660:(.text+0xa1): undefined reference to `libinput_path_remove_device'
/usr/bin/ld: /home/manuel/Documents/PlatformIO/Projects/firmware-elecrow/.pio/libdeps/native-tft/lvgl/src/drivers/libinput/lv_libinput.c:661:(.text+0xad): undefined reference to `libinput_device_unref'
/usr/bin/ld: /home/manuel/Documents/PlatformIO/Projects/firmware-elecrow/.pio/libdeps/native-tft/lvgl/src/drivers/libinput/lv_libinput.c:665:(.text+0xbe): undefined reference to `libinput_unref'
/usr/bin/ld: .pio/build/native-tft/lib5e2/liblvgl.a(lv_libinput.c.o): in function `lv_libinput_query_capability':
/home/manuel/Documents/PlatformIO/Projects/firmware-elecrow/.pio/libdeps/native-tft/lvgl/src/drivers/libinput/lv_libinput.c:96:(.text+0xfb): undefined reference to `libinput_device_has_capability'
```
